import 'server-only';

import { jsPDF } from 'jspdf';

export const PAGE = { width: 210, height: 297, margin: 14, bottom: 280 };

export function splitText(doc: jsPDF, text: string | undefined | null, width: number) {
  return doc.splitTextToSize(text || '', width) as string[];
}

export function ensurePage(doc: jsPDF, y: number, needed = 16) {
  if (y + needed <= PAGE.bottom) return y;
  doc.addPage();
  return PAGE.margin;
}

const LOGO_FETCH_TIMEOUT_MS = 5000;
const MAX_LOGO_BYTES = 2 * 1024 * 1024; // 2MB safety cap

export async function fetchLogoBase64(logoUrl: string | null): Promise<string | null> {
  if (!logoUrl) return null;
  try {
    const response = await fetch(logoUrl, {
      signal: AbortSignal.timeout(LOGO_FETCH_TIMEOUT_MS),
    });
    if (!response.ok || !response.body) return null;

    const chunks: Uint8Array[] = [];
    let total = 0;
    for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) {
      total += chunk.length;
      if (total > MAX_LOGO_BYTES) return null;
      chunks.push(chunk);
    }

    const contentType = response.headers.get('content-type') || 'image/png';
    const buffer = Buffer.concat(chunks);
    return `data:${contentType};base64,${buffer.toString('base64')}`;
  } catch {
    // Logo fetch is best-effort; fall back to text header if it fails,
    // times out, or exceeds the size cap.
    return null;
  }
}

/**
 * Organization contact details (phone/address/website) are stored in
 * `organization.metadata` as a JSON blob (see general-tab.tsx), either
 * already-parsed or as a JSON string depending on the caller.
 */
export function parseOrganizationMetadata(
  metadata: Record<string, unknown> | string | null | undefined
): { phone?: string; address?: string; website?: string } {
  if (!metadata) return {};
  const parsed =
    typeof metadata === 'string'
      ? (() => {
          try {
            return JSON.parse(metadata);
          } catch {
            return {};
          }
        })()
      : metadata;
  return {
    phone: typeof parsed?.phone === 'string' ? parsed.phone : undefined,
    address: typeof parsed?.address === 'string' ? parsed.address : undefined,
    website: typeof parsed?.website === 'string' ? parsed.website : undefined,
  };
}

export type OrgBranding = {
  name: string;
  logoDataUri: string | null;
  phone?: string | null;
  address?: string | null;
  website?: string | null;
};

/** Draws the shared header chrome and returns the y-coordinate where body content should start. */
export function drawStandardHeader(
  doc: jsPDF,
  opts: {
    org: OrgBranding;
    titleLabel: string;
    primaryLine: string;
    secondaryLine?: string;
  }
) {
  const { org, titleLabel, primaryLine, secondaryLine } = opts;

  doc.setFillColor(79, 70, 229); // indigo-600, matches app accent
  doc.rect(0, 0, PAGE.width, 3, 'F');

  if (org.logoDataUri) {
    try {
      doc.addImage(org.logoDataUri, PAGE.margin, 10, 20, 20, undefined, 'FAST');
    } catch {
      // Corrupt/unsupported image format — fall back to text below.
    }
  }

  const textX = org.logoDataUri ? PAGE.margin + 26 : PAGE.margin;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(24, 24, 27);
  doc.text(org.name, textX, 18);

  const detailLines = [org.phone, org.address, org.website].filter(
    (line): line is string => Boolean(line)
  );
  if (detailLines.length > 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(82, 82, 91);
    detailLines
      .slice(0, 3)
      .forEach((line, index) => doc.text(line, textX, 24 + index * 4.5));
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(161, 161, 170);
  doc.text(titleLabel, PAGE.width - PAGE.margin, 18, { align: 'right' });

  doc.setFontSize(10);
  doc.setTextColor(63, 63, 70);
  doc.text(primaryLine, PAGE.width - PAGE.margin, 25, { align: 'right' });

  if (secondaryLine) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(82, 82, 91);
    doc.text(secondaryLine, PAGE.width - PAGE.margin, 31, { align: 'right' });
  }

  doc.setDrawColor(229, 231, 235);
  doc.line(PAGE.margin, 40, PAGE.width - PAGE.margin, 40);

  return 52;
}

export function drawStandardFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(229, 231, 235);
    doc.line(PAGE.margin, 282, PAGE.width - PAGE.margin, 282);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(113, 113, 122);
    doc.text('Generated by PMG Tracker 360', PAGE.margin, 288);
    doc.text(`Page ${i} of ${pageCount}`, PAGE.width - PAGE.margin, 288, { align: 'right' });
  }
}

export type TableColumn = {
  key: string;
  label: string;
  widthMm: number;
  x: number;
  align?: 'left' | 'right';
  wrap?: boolean;
  bold?: boolean;
};

function drawTableHeaderRow(doc: jsPDF, y: number, columns: TableColumn[]) {
  doc.setFillColor(249, 250, 251);
  doc.rect(PAGE.margin, y, PAGE.width - PAGE.margin * 2, 9, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(113, 113, 122);
  for (const col of columns) {
    doc.text(col.label, col.x, y + 6, col.align === 'right' ? { align: 'right' } : undefined);
  }
  return y + 12;
}

/**
 * Generic table renderer with pagination: re-draws the header row whenever
 * a row forces a page break, mirroring po-pdf.ts's original line-items
 * table behavior.
 */
export function drawTable(
  doc: jsPDF,
  opts: {
    startY: number;
    columns: TableColumn[];
    rows: Record<string, string>[];
    emptyMessage?: string;
  }
) {
  const { columns, rows, emptyMessage } = opts;
  let y = drawTableHeaderRow(doc, opts.startY, columns);

  if (rows.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(113, 113, 122);
    doc.text(emptyMessage || 'No records.', PAGE.margin + 2, y + 4);
    return y + 12;
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  for (const row of rows) {
    const wrappedCells = columns.map((col) =>
      col.wrap ? splitText(doc, row[col.key], col.widthMm) : [row[col.key] ?? '']
    );
    const rowHeight = Math.max(10, Math.max(...wrappedCells.map((lines) => lines.length)) * 4 + 4);

    const pageBefore = doc.getNumberOfPages();
    y = ensurePage(doc, y, rowHeight);
    if (doc.getNumberOfPages() !== pageBefore) {
      y = drawTableHeaderRow(doc, y, columns);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
    }

    columns.forEach((col, i) => {
      doc.setTextColor(24, 24, 27);
      doc.setFont('helvetica', col.bold ? 'bold' : 'normal');
      doc.text(wrappedCells[i]!, col.x, y + 4, col.align === 'right' ? { align: 'right' } : undefined);
    });
    doc.setFont('helvetica', 'normal');
    doc.setDrawColor(244, 244, 245);
    doc.line(PAGE.margin, y + rowHeight, PAGE.width - PAGE.margin, y + rowHeight);
    y += rowHeight;
  }

  return y + 6;
}
