CREATE TABLE IF NOT EXISTS "subscription_plan" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"price_zar" integer DEFAULT 0 NOT NULL,
	"period" text DEFAULT 'per month' NOT NULL,
	"max_storage_mb" integer DEFAULT 100 NOT NULL,
	"max_tenders_per_month" integer DEFAULT 10 NOT NULL,
	"max_active_projects" integer DEFAULT 0 NOT NULL,
	"max_owned_orgs" integer DEFAULT 1 NOT NULL,
	"features" jsonb NOT NULL,
	"popular" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"cta_text" text DEFAULT 'Select Plan' NOT NULL,
	"badge_text" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "subscription_plan" (
	"id",
	"name",
	"description",
	"price_zar",
	"period",
	"max_storage_mb",
	"max_tenders_per_month",
	"max_active_projects",
	"max_owned_orgs",
	"features",
	"popular",
	"sort_order",
	"is_active",
	"cta_text",
	"badge_text"
) VALUES
(
	'free',
	'Free Starter',
	'Essential tender tracking & compliance checklist for solo contractors evaluating bids.',
	0,
	'forever free',
	100,
	10,
	0,
	1,
	'["1 Organization Ownership", "Up to 10 Tenders / Month", "0 Active Awarded Projects", "100 MB Secure Document Storage", "Standard Returnable Checklist", "Community Support"]'::jsonb,
	false,
	1,
	true,
	'Start For Free',
	NULL
),
(
	'starter',
	'Starter Tier',
	'Expanded capacity for growing teams managing multiple bids and tracking purchase orders.',
	199,
	'per month',
	1000,
	20,
	2,
	1,
	'["1 Organization Ownership", "Up to 20 Tenders / Month", "2 Active Awarded Projects", "1 GB Secure Storage (10x capacity)", "Itemized Purchase Order Ledger", "Automated Email Deadline Alerts", "Standard Email & Ticket Support"]'::jsonb,
	false,
	2,
	true,
	'Upgrade to Starter',
	NULL
),
(
	'pro',
	'Pro Professional',
	'High-velocity procurement workspace for established contractors with unlimited bidding.',
	499,
	'per month',
	10000,
	-1,
	5,
	2,
	'["2 Organization Ownerships", "Unlimited Tenders Tracked", "5 Active Awarded Projects", "10 GB Secure Storage (100x capacity)", "Itemized PO & Delivery Note Tracking", "Automated Signed URLs & File Protection", "Priority 24/7 Concierge Support (#TICK-1001)"]'::jsonb,
	true,
	3,
	true,
	'Claim Pro Access',
	'Popular'
)
ON CONFLICT ("id") DO UPDATE SET
	"name" = EXCLUDED."name",
	"description" = EXCLUDED."description",
	"price_zar" = EXCLUDED."price_zar",
	"period" = EXCLUDED."period",
	"max_storage_mb" = EXCLUDED."max_storage_mb",
	"max_tenders_per_month" = EXCLUDED."max_tenders_per_month",
	"max_active_projects" = EXCLUDED."max_active_projects",
	"max_owned_orgs" = EXCLUDED."max_owned_orgs",
	"features" = EXCLUDED."features",
	"popular" = EXCLUDED."popular",
	"sort_order" = EXCLUDED."sort_order",
	"is_active" = EXCLUDED."is_active",
	"cta_text" = EXCLUDED."cta_text",
	"badge_text" = EXCLUDED."badge_text",
	"updated_at" = now();
